### ISSUE TITLE
How can I avoid to Make ROS Logs Saver desktop icon?

### ISSUE THREAD

**Issue by Charlie0257** [shadow-robot/aurora#487]
When I build the gazebo simulation, I ran the command as follows:
`bash <(curl -Ls bit.ly/run-aurora) docker_deploy product=hand_e sim_hand=true container_name=dexterous_hand_simulated  tag=melodic-release launch_hand=true desktop_icon=false demo_icons=false nvidia_docker=true
`
But there is an error shown——
`TASK [products/common/save-logs-icons : Make ROS Logs Saver desktop icon trusted] ******************************************************************************************
task path: /tmp/aurora/ansible/roles/products/common/save-logs-icons/tasks/main.yml:39
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "gio set \"/home/charlie/Desktop/Shadow ROS Logs Saver.desktop\" \"metadata::trusted\" yes", "delta": "0:00:00.004690", "end": "2022-08-18 10:17:01.531961", "msg": "non-zero return code", "rc": 1, "start": "2022-08-18 10:17:01.527271", "stderr": "gio: Setting attribute metadata::trusted not supported", "stderr_lines": ["gio: Setting attribute metadata::trusted not supported"], "stdout": "", "stdout_lines": []}
`
How can I avoid or solve this problem?
Thank you.

**Comment by BenStarmerSmith** [comment]
Hey,
Can you tell me abit about the system you are running, such as what version of Ubuntu you are running?

**Comment by Charlie0257** [comment]
Ubuntu 18.04.5 LTS
NVIDIA GeForce RTX 3070/PCIe/SSE2
Intel® Xeon(R) W-1250 CPU @ 3.30GHz × 12

**Comment by BenStarmerSmith** [comment]
Can you try this oneliner as our last tested version of aurora with melodic was 1.1.6:
`bash <(curl -Ls https://raw.githubusercontent.com/shadow-robot/aurora/1.1.6/bin/run-ansible.sh) docker_deploy --branch 1.1.6 product=hand_e sim_hand=true container_name=dexterous_hand_simulated tag=melodic-release launch_hand=true desktop_icon=false demo_icons=false nvidia_docker=true`

**Comment by Charlie0257** [comment]
New commend will have an error when pulling the image:
`TASK [docker/docker-image : Pull Docker image] *********************************
task path: /tmp/aurora/ansible/roles/docker/docker-image/tasks/main.yml:24
fatal: [127.0.0.1]: FAILED! => {"msg": "Could not find imported module support code for ansible_collections.community.docker.plugins.modules.docker_image.  Looked for (['ansible.module_utils.compat.version.LooseVersion', 'ansible.module_utils.compat.version'])"}`

`TASK [docker/docker-image : Temporary error in docker pull. Automatically waiting 10 seconds before trying again. If it still fails, re-run the aurora script] ***
task path: /tmp/aurora/ansible/roles/docker/docker-image/tasks/main.yml:45
ok: [127.0.0.1] => {"changed": false, "elapsed": 10, "match_groupdict": {}, "match_groups": [], "path": null, "port": null, "search_regex": null, "state": "started"}`

`TASK [docker/docker-image : Pull Docker image (attempt 2)] *********************
task path: /tmp/aurora/ansible/roles/docker/docker-image/tasks/main.yml:49
fatal: [127.0.0.1]: FAILED! => {"msg": "Could not find imported module support code for ansible_collections.community.docker.plugins.modules.docker_image.  Looked for (['ansible.module_utils.compat.version.LooseVersion', 'ansible.module_utils.compat.version'])"}
`

**Comment by BenStarmerSmith** [comment]
Did you restart your computer after running the tool for the first time? You need to run the tool once to setup docker, then restart it and rerun it again to fully install everything

**Comment by Charlie0257** [comment]
Yes, I did. 
The new command line does not seem to give a wait time for pulling the image :(
I can pull the image with no problem using the old command line.

**Comment by BenStarmerSmith** [comment]
Unfortuantly Ansible (which is the tool Aurora uses) doesn't give status about the pulling process it just leaves messages telling you that it's still pulling, it might just take awhile for it to pull. If you want the status you can always pull the image manually by doing: `docker pull shadowrobot/dexterous-hand:melodic-release`. then once that's pulled running the oneliner I gave you.

**Comment by Charlie0257** [comment]
It seems to be related to the version of `Ansible`. The version of `Ansible` used on the command line in the old was `ansible_core-2.11.10.dist-info`, while the version of `Ansible` used for the unpullable image was `ansible_base-2.10.7.dist-info`.

I'm not sure if this is the reason. Could you please check it

**Comment by Charlie0257** [comment]
The good news is that it can be visualized properly in `Mujoco`! :)
Could you send me a GitHub link to the `UR_Arm` + `Shadow_Hand` environment in `Mujoco` without the usage of `Rviz`?

Thank you! :)
